game:
  server-name: "Sumo-01"
  map-name: "Forest"
  spawns:
    red:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    blue:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    spectate:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0